# Generated by Django 4.2.6 on 2023-10-31 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("slug", models.SlugField()),
                ("description", models.TextField()),
                ("discount", models.FloatField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
            options={
                "ordering": ["title", "end_date", "start_date"],
                "indexes": [
                    models.Index(
                        fields=["title", "discount"],
                        name="store_promo_title_017412_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="store_promo_start_d_233727_idx",
                    ),
                ],
            },
        ),
    ]
