# Generated by Django 4.2.6 on 2023-10-31 18:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_collection_featured_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="stock",
                        serialize=False,
                        to="store.product",
                    ),
                ),
                (
                    "quantity_in_stock",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
            options={
                "ordering": ["quantity_in_stock"],
                "indexes": [
                    models.Index(
                        fields=["quantity_in_stock", "threshold"],
                        name="store_stock_quantit_1b15b6_idx",
                    ),
                    models.Index(
                        fields=["product", "quantity_in_stock"],
                        name="store_stock_product_15be73_idx",
                    ),
                ],
            },
        ),
    ]
