# Generated by Django 4.2.6 on 2023-10-31 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_cart_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("S", "Shipped"),
                            ("D", "Delivered"),
                            ("C", "Picked Up"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("F", "Failed"), ("C", "Complete"), ("P", "Pending")],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="store.customer",
                    ),
                ),
            ],
        ),
    ]
