# Generated by Django 4.2.6 on 2023-10-31 18:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item",
                        to="store.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "ordering": ["quantity", "unit_price"],
                "indexes": [
                    models.Index(
                        fields=["order", "product"],
                        name="store_order_order_i_ec571c_idx",
                    ),
                    models.Index(
                        fields=["quantity", "unit_price"],
                        name="store_order_quantit_623004_idx",
                    ),
                ],
            },
        ),
    ]
